// Generated by purs bundle 0.12.0
export var PS = {};
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Semigroupoid = function (compose) {
      this.compose = compose;
  };
  var semigroupoidFn = new Semigroupoid(function (f) {
      return function (g) {
          return function (x) {
              return f(g(x));
          };
      };
  });
  var compose = function (dict) {
      return dict.compose;
  };
  exports["compose"] = compose;
  exports["Semigroupoid"] = Semigroupoid;
  exports["semigroupoidFn"] = semigroupoidFn;
})(PS["Control.Semigroupoid"] = PS["Control.Semigroupoid"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Semigroupoid = PS["Control.Semigroupoid"];                 
  var Category = function (Semigroupoid0, identity) {
      this.Semigroupoid0 = Semigroupoid0;
      this.identity = identity;
  };
  var identity = function (dict) {
      return dict.identity;
  };
  var categoryFn = new Category(function () {
      return Control_Semigroupoid.semigroupoidFn;
  }, function (x) {
      return x;
  });
  exports["Category"] = Category;
  exports["identity"] = identity;
  exports["categoryFn"] = categoryFn;
})(PS["Control.Category"] = PS["Control.Category"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var otherwise = true;
  exports["otherwise"] = otherwise;
})(PS["Data.Boolean"] = PS["Data.Boolean"] || {});
(function(exports) {
    "use strict";

  exports.refEq = function (r1) {
    return function (r2) {
      return r1 === r2;
    };
  };
})(PS["Data.Eq"] = PS["Data.Eq"] || {});
(function(exports) {
    "use strict";

  exports.unit = {};
})(PS["Data.Unit"] = PS["Data.Unit"] || {});
(function(exports) {
    "use strict";

  exports.showStringImpl = function (s) {
    var l = s.length;
    return "\"" + s.replace(
      /[\0-\x1F\x7F"\\]/g, // eslint-disable-line no-control-regex
      function (c, i) {
        switch (c) {
          case "\"":
          case "\\":
            return "\\" + c;
          case "\x07": return "\\a";
          case "\b": return "\\b";
          case "\f": return "\\f";
          case "\n": return "\\n";
          case "\r": return "\\r";
          case "\t": return "\\t";
          case "\v": return "\\v";
        }
        var k = i + 1;
        var empty = k < l && s[k] >= "0" && s[k] <= "9" ? "\\&" : "";
        return "\\" + c.charCodeAt(0).toString(10) + empty;
      }
    ) + "\"";
  };

  exports.showArrayImpl = function (f) {
    return function (xs) {
      var ss = [];
      for (var i = 0, l = xs.length; i < l; i++) {
        ss[i] = f(xs[i]);
      }
      return "[" + ss.join(",") + "]";
    };
  };

  exports.join = function (separator) {
    return function (xs) {
      return xs.join(separator);
    };
  };
})(PS["Data.Show"] = PS["Data.Show"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Data.Show"];
  var Data_Symbol = PS["Data.Symbol"];
  var Record_Unsafe = PS["Record.Unsafe"];
  var Type_Data_RowList = PS["Type.Data.RowList"];                 
  var Show = function (show) {
      this.show = show;
  };
  var showString = new Show($foreign.showStringImpl);
  var show = function (dict) {
      return dict.show;
  };
  var showArray = function (dictShow) {
      return new Show($foreign.showArrayImpl(show(dictShow)));
  };
  exports["Show"] = Show;
  exports["show"] = show;
  exports["showString"] = showString;
  exports["showArray"] = showArray;
})(PS["Data.Show"] = PS["Data.Show"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Data.Unit"];
  var Data_Show = PS["Data.Show"];
  exports["unit"] = $foreign.unit;
})(PS["Data.Unit"] = PS["Data.Unit"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Data.Eq"];
  var Data_HeytingAlgebra = PS["Data.HeytingAlgebra"];
  var Data_Symbol = PS["Data.Symbol"];
  var Data_Unit = PS["Data.Unit"];
  var Data_Void = PS["Data.Void"];
  var Record_Unsafe = PS["Record.Unsafe"];
  var Type_Data_RowList = PS["Type.Data.RowList"];                 
  var Eq = function (eq) {
      this.eq = eq;
  };                                    
  var eqInt = new Eq($foreign.refEq);
  var eq = function (dict) {
      return dict.eq;
  };
  exports["Eq"] = Eq;
  exports["eq"] = eq;
  exports["eqInt"] = eqInt;
})(PS["Data.Eq"] = PS["Data.Eq"] || {});
(function(exports) {
    "use strict";

  exports.unsafeCompareImpl = function (lt) {
    return function (eq) {
      return function (gt) {
        return function (x) {
          return function (y) {
            return x < y ? lt : x === y ? eq : gt;
          };
        };
      };
    };
  };
})(PS["Data.Ord.Unsafe"] = PS["Data.Ord.Unsafe"] || {});
(function(exports) {
    "use strict";

  exports.concatString = function (s1) {
    return function (s2) {
      return s1 + s2;
    };
  };

  exports.concatArray = function (xs) {
    return function (ys) {
      if (xs.length === 0) return ys;
      if (ys.length === 0) return xs;
      return xs.concat(ys);
    };
  };
})(PS["Data.Semigroup"] = PS["Data.Semigroup"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Data.Semigroup"];
  var Data_Symbol = PS["Data.Symbol"];
  var Data_Unit = PS["Data.Unit"];
  var Data_Void = PS["Data.Void"];
  var Record_Unsafe = PS["Record.Unsafe"];
  var Type_Data_RowList = PS["Type.Data.RowList"];                 
  var Semigroup = function (append) {
      this.append = append;
  }; 
  var semigroupString = new Semigroup($foreign.concatString);
  var semigroupArray = new Semigroup($foreign.concatArray);
  var append = function (dict) {
      return dict.append;
  };
  exports["Semigroup"] = Semigroup;
  exports["append"] = append;
  exports["semigroupString"] = semigroupString;
  exports["semigroupArray"] = semigroupArray;
})(PS["Data.Semigroup"] = PS["Data.Semigroup"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Data_Eq = PS["Data.Eq"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Show = PS["Data.Show"];                 
  var LT = (function () {
      function LT() {

      };
      LT.value = new LT();
      return LT;
  })();
  var GT = (function () {
      function GT() {

      };
      GT.value = new GT();
      return GT;
  })();
  var EQ = (function () {
      function EQ() {

      };
      EQ.value = new EQ();
      return EQ;
  })();
  exports["LT"] = LT;
  exports["GT"] = GT;
  exports["EQ"] = EQ;
})(PS["Data.Ordering"] = PS["Data.Ordering"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Data.Ord.Unsafe"];
  var Data_Ordering = PS["Data.Ordering"];                 
  var unsafeCompare = $foreign.unsafeCompareImpl(Data_Ordering.LT.value)(Data_Ordering.EQ.value)(Data_Ordering.GT.value);
  exports["unsafeCompare"] = unsafeCompare;
})(PS["Data.Ord.Unsafe"] = PS["Data.Ord.Unsafe"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Data.Ord"];
  var Data_Eq = PS["Data.Eq"];
  var Data_Ord_Unsafe = PS["Data.Ord.Unsafe"];
  var Data_Ordering = PS["Data.Ordering"];
  var Data_Ring = PS["Data.Ring"];
  var Data_Semiring = PS["Data.Semiring"];
  var Data_Symbol = PS["Data.Symbol"];
  var Data_Unit = PS["Data.Unit"];
  var Data_Void = PS["Data.Void"];
  var Record_Unsafe = PS["Record.Unsafe"];
  var Type_Data_RowList = PS["Type.Data.RowList"];                 
  var Ord = function (Eq0, compare) {
      this.Eq0 = Eq0;
      this.compare = compare;
  };                                
  var ordInt = new Ord(function () {
      return Data_Eq.eqInt;
  }, Data_Ord_Unsafe.unsafeCompare);
  var compare = function (dict) {
      return dict.compare;
  };
  exports["Ord"] = Ord;
  exports["compare"] = compare;
  exports["ordInt"] = ordInt;
})(PS["Data.Ord"] = PS["Data.Ord"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Category = PS["Control.Category"];
  var Data_Boolean = PS["Data.Boolean"];
  var Data_Ord = PS["Data.Ord"];
  var Data_Ring = PS["Data.Ring"];
  var flip = function (f) {
      return function (b) {
          return function (a) {
              return f(a)(b);
          };
      };
  };
  var applyFlipped = function (x) {
      return function (f) {
          return f(x);
      };
  };
  exports["flip"] = flip;
  exports["applyFlipped"] = applyFlipped;
})(PS["Data.Function"] = PS["Data.Function"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Data_Function = PS["Data.Function"];
  var Prelude = PS["Prelude"];                 
  var pipeForward = Data_Function.applyFlipped;
  exports["pipeForward"] = pipeForward;
})(PS["Common.Annex"] = PS["Common.Annex"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Data.Functor"];
  var Control_Semigroupoid = PS["Control.Semigroupoid"];
  var Data_Function = PS["Data.Function"];
  var Data_Unit = PS["Data.Unit"];                 
  var Functor = function (map) {
      this.map = map;
  };
  var map = function (dict) {
      return dict.map;
  };
  exports["Functor"] = Functor;
  exports["map"] = map;
})(PS["Data.Functor"] = PS["Data.Functor"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Control.Apply"];
  var Control_Category = PS["Control.Category"];
  var Data_Function = PS["Data.Function"];
  var Data_Functor = PS["Data.Functor"];                 
  var Apply = function (Functor0, apply) {
      this.Functor0 = Functor0;
      this.apply = apply;
  };                      
  var apply = function (dict) {
      return dict.apply;
  };
  exports["Apply"] = Apply;
  exports["apply"] = apply;
})(PS["Control.Apply"] = PS["Control.Apply"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Control.Bind"];
  var Control_Applicative = PS["Control.Applicative"];
  var Control_Apply = PS["Control.Apply"];
  var Control_Category = PS["Control.Category"];
  var Data_Function = PS["Data.Function"];
  var Data_Functor = PS["Data.Functor"];
  var Data_Unit = PS["Data.Unit"];                 
  var Bind = function (Apply0, bind) {
      this.Apply0 = Apply0;
      this.bind = bind;
  };
  var Discard = function (discard) {
      this.discard = discard;
  };
  var discard = function (dict) {
      return dict.discard;
  };                     
  var bind = function (dict) {
      return dict.bind;
  };
  var discardUnit = new Discard(function (dictBind) {
      return bind(dictBind);
  });
  exports["Bind"] = Bind;
  exports["bind"] = bind;
  exports["Discard"] = Discard;
  exports["discard"] = discard;
  exports["discardUnit"] = discardUnit;
})(PS["Control.Bind"] = PS["Control.Bind"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Data.Bounded"];
  var Data_Ord = PS["Data.Ord"];
  var Data_Ordering = PS["Data.Ordering"];
  var Data_Unit = PS["Data.Unit"];                 
  var Bounded = function (Ord0, bottom, top) {
      this.Ord0 = Ord0;
      this.bottom = bottom;
      this.top = top;
  };
  var top = function (dict) {
      return dict.top;
  };              
  var bottom = function (dict) {
      return dict.bottom;
  };
  exports["Bounded"] = Bounded;
  exports["bottom"] = bottom;
  exports["top"] = top;
})(PS["Data.Bounded"] = PS["Data.Bounded"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Data_Boolean = PS["Data.Boolean"];
  var Data_Eq = PS["Data.Eq"];
  var Data_EuclideanRing = PS["Data.EuclideanRing"];
  var Data_Ord = PS["Data.Ord"];
  var Data_Ordering = PS["Data.Ordering"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Symbol = PS["Data.Symbol"];
  var Data_Unit = PS["Data.Unit"];
  var Record_Unsafe = PS["Record.Unsafe"];
  var Type_Data_RowList = PS["Type.Data.RowList"];                 
  var Monoid = function (Semigroup0, mempty) {
      this.Semigroup0 = Semigroup0;
      this.mempty = mempty;
  };                 
  var monoidString = new Monoid(function () {
      return Data_Semigroup.semigroupString;
  }, "");
  var mempty = function (dict) {
      return dict.mempty;
  };
  exports["Monoid"] = Monoid;
  exports["mempty"] = mempty;
  exports["monoidString"] = monoidString;
})(PS["Data.Monoid"] = PS["Data.Monoid"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Alt = PS["Control.Alt"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Applicative = PS["Control.Applicative"];
  var Control_Apply = PS["Control.Apply"];
  var Control_Bind = PS["Control.Bind"];
  var Control_Category = PS["Control.Category"];
  var Control_Extend = PS["Control.Extend"];
  var Control_Monad = PS["Control.Monad"];
  var Control_MonadZero = PS["Control.MonadZero"];
  var Control_Plus = PS["Control.Plus"];
  var Data_Bounded = PS["Data.Bounded"];
  var Data_Eq = PS["Data.Eq"];
  var Data_Function = PS["Data.Function"];
  var Data_Functor = PS["Data.Functor"];
  var Data_Functor_Invariant = PS["Data.Functor.Invariant"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Ord = PS["Data.Ord"];
  var Data_Ordering = PS["Data.Ordering"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Show = PS["Data.Show"];
  var Data_Unit = PS["Data.Unit"];
  var Prelude = PS["Prelude"];                 
  var Nothing = (function () {
      function Nothing() {

      };
      Nothing.value = new Nothing();
      return Nothing;
  })();
  var Just = (function () {
      function Just(value0) {
          this.value0 = value0;
      };
      Just.create = function (value0) {
          return new Just(value0);
      };
      return Just;
  })();
  var fromJust = function (dictPartial) {
      return function (v) {
          var $__unused = function (dictPartial1) {
              return function ($dollar35) {
                  return $dollar35;
              };
          };
          return $__unused(dictPartial)((function () {
              if (v instanceof Just) {
                  return v.value0;
              };
              throw new Error("Failed pattern match at Data.Maybe line 269, column 1 - line 269, column 46: " + [ v.constructor.name ]);
          })());
      };
  };
  exports["Nothing"] = Nothing;
  exports["Just"] = Just;
  exports["fromJust"] = fromJust;
})(PS["Data.Maybe"] = PS["Data.Maybe"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Data.Foldable"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Applicative = PS["Control.Applicative"];
  var Control_Apply = PS["Control.Apply"];
  var Control_Bind = PS["Control.Bind"];
  var Control_Category = PS["Control.Category"];
  var Control_Plus = PS["Control.Plus"];
  var Control_Semigroupoid = PS["Control.Semigroupoid"];
  var Data_Eq = PS["Data.Eq"];
  var Data_Function = PS["Data.Function"];
  var Data_Functor = PS["Data.Functor"];
  var Data_HeytingAlgebra = PS["Data.HeytingAlgebra"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Maybe_First = PS["Data.Maybe.First"];
  var Data_Maybe_Last = PS["Data.Maybe.Last"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Monoid_Additive = PS["Data.Monoid.Additive"];
  var Data_Monoid_Conj = PS["Data.Monoid.Conj"];
  var Data_Monoid_Disj = PS["Data.Monoid.Disj"];
  var Data_Monoid_Dual = PS["Data.Monoid.Dual"];
  var Data_Monoid_Endo = PS["Data.Monoid.Endo"];
  var Data_Monoid_Multiplicative = PS["Data.Monoid.Multiplicative"];
  var Data_Newtype = PS["Data.Newtype"];
  var Data_Ord = PS["Data.Ord"];
  var Data_Ordering = PS["Data.Ordering"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Semiring = PS["Data.Semiring"];
  var Data_Unit = PS["Data.Unit"];
  var Prelude = PS["Prelude"];                 
  var Foldable = function (foldMap, foldl, foldr) {
      this.foldMap = foldMap;
      this.foldl = foldl;
      this.foldr = foldr;
  };
  var foldr = function (dict) {
      return dict.foldr;
  };
  var foldl = function (dict) {
      return dict.foldl;
  };
  var intercalate = function (dictFoldable) {
      return function (dictMonoid) {
          return function (sep) {
              return function (xs) {
                  var go = function (v) {
                      return function (x) {
                          if (v.init) {
                              return {
                                  init: false,
                                  acc: x
                              };
                          };
                          return {
                              init: false,
                              acc: Data_Semigroup.append(dictMonoid.Semigroup0())(v.acc)(Data_Semigroup.append(dictMonoid.Semigroup0())(sep)(x))
                          };
                      };
                  };
                  return (foldl(dictFoldable)(go)({
                      init: true,
                      acc: Data_Monoid.mempty(dictMonoid)
                  })(xs)).acc;
              };
          };
      };
  };
  var foldMap = function (dict) {
      return dict.foldMap;
  };
  exports["Foldable"] = Foldable;
  exports["foldr"] = foldr;
  exports["foldl"] = foldl;
  exports["foldMap"] = foldMap;
  exports["intercalate"] = intercalate;
})(PS["Data.Foldable"] = PS["Data.Foldable"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Applicative = PS["Control.Applicative"];
  var Control_Apply = PS["Control.Apply"];
  var Control_Biapplicative = PS["Control.Biapplicative"];
  var Control_Biapply = PS["Control.Biapply"];
  var Control_Bind = PS["Control.Bind"];
  var Control_Comonad = PS["Control.Comonad"];
  var Control_Extend = PS["Control.Extend"];
  var Control_Lazy = PS["Control.Lazy"];
  var Control_Monad = PS["Control.Monad"];
  var Control_Semigroupoid = PS["Control.Semigroupoid"];
  var Data_Bifoldable = PS["Data.Bifoldable"];
  var Data_Bifunctor = PS["Data.Bifunctor"];
  var Data_Bitraversable = PS["Data.Bitraversable"];
  var Data_BooleanAlgebra = PS["Data.BooleanAlgebra"];
  var Data_Bounded = PS["Data.Bounded"];
  var Data_CommutativeRing = PS["Data.CommutativeRing"];
  var Data_Distributive = PS["Data.Distributive"];
  var Data_Eq = PS["Data.Eq"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_Function = PS["Data.Function"];
  var Data_Functor = PS["Data.Functor"];
  var Data_Functor_Invariant = PS["Data.Functor.Invariant"];
  var Data_HeytingAlgebra = PS["Data.HeytingAlgebra"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Maybe_First = PS["Data.Maybe.First"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Newtype = PS["Data.Newtype"];
  var Data_Ord = PS["Data.Ord"];
  var Data_Ordering = PS["Data.Ordering"];
  var Data_Ring = PS["Data.Ring"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Semiring = PS["Data.Semiring"];
  var Data_Show = PS["Data.Show"];
  var Data_Traversable = PS["Data.Traversable"];
  var Data_Unit = PS["Data.Unit"];
  var Prelude = PS["Prelude"];
  var Type_Equality = PS["Type.Equality"];                 
  var Tuple = (function () {
      function Tuple(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      Tuple.create = function (value0) {
          return function (value1) {
              return new Tuple(value0, value1);
          };
      };
      return Tuple;
  })();
  exports["Tuple"] = Tuple;
})(PS["Data.Tuple"] = PS["Data.Tuple"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var $foreign = PS["Data.Enum"];
  var Control_Apply = PS["Control.Apply"];
  var Control_Bind = PS["Control.Bind"];
  var Control_MonadPlus = PS["Control.MonadPlus"];
  var Control_MonadZero = PS["Control.MonadZero"];
  var Control_Semigroupoid = PS["Control.Semigroupoid"];
  var Data_Boolean = PS["Data.Boolean"];
  var Data_Bounded = PS["Data.Bounded"];
  var Data_Either = PS["Data.Either"];
  var Data_Eq = PS["Data.Eq"];
  var Data_Function = PS["Data.Function"];
  var Data_Functor = PS["Data.Functor"];
  var Data_HeytingAlgebra = PS["Data.HeytingAlgebra"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Newtype = PS["Data.Newtype"];
  var Data_Ord = PS["Data.Ord"];
  var Data_Ordering = PS["Data.Ordering"];
  var Data_Ring = PS["Data.Ring"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Semiring = PS["Data.Semiring"];
  var Data_Show = PS["Data.Show"];
  var Data_Tuple = PS["Data.Tuple"];
  var Data_Unfoldable = PS["Data.Unfoldable"];
  var Data_Unfoldable1 = PS["Data.Unfoldable1"];
  var Data_Unit = PS["Data.Unit"];
  var Partial_Unsafe = PS["Partial.Unsafe"];
  var Prelude = PS["Prelude"];
  var Enum = function (Ord0, pred, succ) {
      this.Ord0 = Ord0;
      this.pred = pred;
      this.succ = succ;
  };
  var BoundedEnum = function (Bounded0, Enum1, cardinality, fromEnum, toEnum) {
      this.Bounded0 = Bounded0;
      this.Enum1 = Enum1;
      this.cardinality = cardinality;
      this.fromEnum = fromEnum;
      this.toEnum = toEnum;
  };
  var toEnum = function (dict) {
      return dict.toEnum;
  };
  var succ = function (dict) {
      return dict.succ;
  }; 
  var pred = function (dict) {
      return dict.pred;
  };              
  var fromEnum = function (dict) {
      return dict.fromEnum;
  };                                                                                             
  var cardinality = function (dict) {
      return dict.cardinality;
  };
  exports["Enum"] = Enum;
  exports["succ"] = succ;
  exports["pred"] = pred;
  exports["BoundedEnum"] = BoundedEnum;
  exports["cardinality"] = cardinality;
  exports["toEnum"] = toEnum;
  exports["fromEnum"] = fromEnum;
})(PS["Data.Enum"] = PS["Data.Enum"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Alt = PS["Control.Alt"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Applicative = PS["Control.Applicative"];
  var Control_Apply = PS["Control.Apply"];
  var Control_Bind = PS["Control.Bind"];
  var Control_Category = PS["Control.Category"];
  var Control_Comonad = PS["Control.Comonad"];
  var Control_Extend = PS["Control.Extend"];
  var Control_Monad = PS["Control.Monad"];
  var Control_MonadPlus = PS["Control.MonadPlus"];
  var Control_MonadZero = PS["Control.MonadZero"];
  var Control_Plus = PS["Control.Plus"];
  var Control_Semigroupoid = PS["Control.Semigroupoid"];
  var Data_Eq = PS["Data.Eq"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_FoldableWithIndex = PS["Data.FoldableWithIndex"];
  var Data_Function = PS["Data.Function"];
  var Data_Functor = PS["Data.Functor"];
  var Data_FunctorWithIndex = PS["Data.FunctorWithIndex"];
  var Data_HeytingAlgebra = PS["Data.HeytingAlgebra"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Newtype = PS["Data.Newtype"];
  var Data_NonEmpty = PS["Data.NonEmpty"];
  var Data_Ord = PS["Data.Ord"];
  var Data_Ordering = PS["Data.Ordering"];
  var Data_Ring = PS["Data.Ring"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Semigroup_Foldable = PS["Data.Semigroup.Foldable"];
  var Data_Semigroup_Traversable = PS["Data.Semigroup.Traversable"];
  var Data_Semiring = PS["Data.Semiring"];
  var Data_Show = PS["Data.Show"];
  var Data_Traversable = PS["Data.Traversable"];
  var Data_TraversableWithIndex = PS["Data.TraversableWithIndex"];
  var Data_Tuple = PS["Data.Tuple"];
  var Data_Unfoldable = PS["Data.Unfoldable"];
  var Data_Unfoldable1 = PS["Data.Unfoldable1"];
  var Prelude = PS["Prelude"];                 
  var Nil = (function () {
      function Nil() {

      };
      Nil.value = new Nil();
      return Nil;
  })();
  var Cons = (function () {
      function Cons(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      Cons.create = function (value0) {
          return function (value1) {
              return new Cons(value0, value1);
          };
      };
      return Cons;
  })();
  var foldableList = new Data_Foldable.Foldable(function (dictMonoid) {
      return function (f) {
          return Data_Foldable.foldl(foldableList)(function (acc) {
              return function ($155) {
                  return Data_Semigroup.append(dictMonoid.Semigroup0())(acc)(f($155));
              };
          })(Data_Monoid.mempty(dictMonoid));
      };
  }, function (f) {
      var go = function ($copy_b) {
          return function ($copy_v) {
              var $tco_var_b = $copy_b;
              var $tco_done = false;
              var $tco_result;
              function $tco_loop(b, v) {
                  if (v instanceof Nil) {
                      $tco_done = true;
                      return b;
                  };
                  if (v instanceof Cons) {
                      $tco_var_b = f(b)(v.value0);
                      $copy_v = v.value1;
                      return;
                  };
                  throw new Error("Failed pattern match at Data.List.Types line 81, column 12 - line 83, column 30: " + [ v.constructor.name ]);
              };
              while (!$tco_done) {
                  $tco_result = $tco_loop($tco_var_b, $copy_v);
              };
              return $tco_result;
          };
      };
      return go;
  }, function (f) {
      return function (b) {
          var rev = Data_Foldable.foldl(foldableList)(Data_Function.flip(Cons.create))(Nil.value);
          return function ($156) {
              return Data_Foldable.foldl(foldableList)(Data_Function.flip(f))(b)(rev($156));
          };
      };
  });
  var functorList = new Data_Functor.Functor(function (f) {
      return Data_Foldable.foldr(foldableList)(function (x) {
          return function (acc) {
              return new Cons(f(x), acc);
          };
      })(Nil.value);
  });
  var semigroupList = new Data_Semigroup.Semigroup(function (xs) {
      return function (ys) {
          return Data_Foldable.foldr(foldableList)(Cons.create)(ys)(xs);
      };
  });
  var showList = function (dictShow) {
      return new Data_Show.Show(function (v) {
          if (v instanceof Nil) {
              return "Nil";
          };
          return "(" + (Data_Foldable.intercalate(foldableList)(Data_Monoid.monoidString)(" : ")(Data_Functor.map(functorList)(Data_Show.show(dictShow))(v)) + " : Nil)");
      });
  };
  exports["Nil"] = Nil;
  exports["Cons"] = Cons;
  exports["showList"] = showList;
  exports["semigroupList"] = semigroupList;
  exports["functorList"] = functorList;
  exports["foldableList"] = foldableList;
})(PS["Data.List.Types"] = PS["Data.List.Types"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Alt = PS["Control.Alt"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Applicative = PS["Control.Applicative"];
  var Control_Apply = PS["Control.Apply"];
  var Control_Bind = PS["Control.Bind"];
  var Control_Category = PS["Control.Category"];
  var Control_Lazy = PS["Control.Lazy"];
  var Control_Monad_Rec_Class = PS["Control.Monad.Rec.Class"];
  var Control_Semigroupoid = PS["Control.Semigroupoid"];
  var Data_Bifunctor = PS["Data.Bifunctor"];
  var Data_Boolean = PS["Data.Boolean"];
  var Data_Eq = PS["Data.Eq"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_Function = PS["Data.Function"];
  var Data_Functor = PS["Data.Functor"];
  var Data_FunctorWithIndex = PS["Data.FunctorWithIndex"];
  var Data_HeytingAlgebra = PS["Data.HeytingAlgebra"];
  var Data_List_Types = PS["Data.List.Types"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Newtype = PS["Data.Newtype"];
  var Data_NonEmpty = PS["Data.NonEmpty"];
  var Data_Ord = PS["Data.Ord"];
  var Data_Ordering = PS["Data.Ordering"];
  var Data_Ring = PS["Data.Ring"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Semiring = PS["Data.Semiring"];
  var Data_Show = PS["Data.Show"];
  var Data_Traversable = PS["Data.Traversable"];
  var Data_Tuple = PS["Data.Tuple"];
  var Data_Unfoldable = PS["Data.Unfoldable"];
  var Data_Unit = PS["Data.Unit"];
  var Prelude = PS["Prelude"];
  var snoc = function (xs) {
      return function (x) {
          return Data_Foldable.foldr(Data_List_Types.foldableList)(Data_List_Types.Cons.create)(new Data_List_Types.Cons(x, Data_List_Types.Nil.value))(xs);
      };
  };
  var singleton = function (a) {
      return new Data_List_Types.Cons(a, Data_List_Types.Nil.value);
  };
  exports["singleton"] = singleton;
  exports["snoc"] = snoc;
})(PS["Data.List"] = PS["Data.List"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Semigroupoid = PS["Control.Semigroupoid"];
  var Data_Boolean = PS["Data.Boolean"];
  var Data_Bounded = PS["Data.Bounded"];
  var Data_Enum = PS["Data.Enum"];
  var Data_Eq = PS["Data.Eq"];
  var Data_HeytingAlgebra = PS["Data.HeytingAlgebra"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Ord = PS["Data.Ord"];
  var Data_Ring = PS["Data.Ring"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Semiring = PS["Data.Semiring"];
  var Data_Show = PS["Data.Show"];
  var Prelude = PS["Prelude"];
  var ordSecond = Data_Ord.ordInt;
  var ordMinute = Data_Ord.ordInt;
  var ordMillisecond = Data_Ord.ordInt;
  var ordHour = Data_Ord.ordInt;
  var boundedSecond = new Data_Bounded.Bounded(function () {
      return ordSecond;
  }, 0, 59);
  var boundedMinute = new Data_Bounded.Bounded(function () {
      return ordMinute;
  }, 0, 59);
  var boundedMillisecond = new Data_Bounded.Bounded(function () {
      return ordMillisecond;
  }, 0, 999);
  var boundedHour = new Data_Bounded.Bounded(function () {
      return ordHour;
  }, 0, 23);
  var boundedEnumSecond = new Data_Enum.BoundedEnum(function () {
      return boundedSecond;
  }, function () {
      return enumSecond;
  }, 60, function (v) {
      return v;
  }, function (n) {
      if (n >= 0 && n <= 59) {
          return new Data_Maybe.Just(n);
      };
      if (Data_Boolean.otherwise) {
          return Data_Maybe.Nothing.value;
      };
      throw new Error("Failed pattern match at Data.Time.Component line 90, column 1 - line 90, column 49: " + [ n.constructor.name ]);
  });
  var enumSecond = new Data_Enum.Enum(function () {
      return ordSecond;
  }, function ($28) {
      return Data_Enum.toEnum(boundedEnumSecond)((function (v) {
          return v - 1 | 0;
      })(Data_Enum.fromEnum(boundedEnumSecond)($28)));
  }, function ($29) {
      return Data_Enum.toEnum(boundedEnumSecond)((function (v) {
          return v + 1 | 0;
      })(Data_Enum.fromEnum(boundedEnumSecond)($29)));
  });
  var boundedEnumMinute = new Data_Enum.BoundedEnum(function () {
      return boundedMinute;
  }, function () {
      return enumMinute;
  }, 60, function (v) {
      return v;
  }, function (n) {
      if (n >= 0 && n <= 59) {
          return new Data_Maybe.Just(n);
      };
      if (Data_Boolean.otherwise) {
          return Data_Maybe.Nothing.value;
      };
      throw new Error("Failed pattern match at Data.Time.Component line 61, column 1 - line 61, column 49: " + [ n.constructor.name ]);
  });
  var enumMinute = new Data_Enum.Enum(function () {
      return ordMinute;
  }, function ($30) {
      return Data_Enum.toEnum(boundedEnumMinute)((function (v) {
          return v - 1 | 0;
      })(Data_Enum.fromEnum(boundedEnumMinute)($30)));
  }, function ($31) {
      return Data_Enum.toEnum(boundedEnumMinute)((function (v) {
          return v + 1 | 0;
      })(Data_Enum.fromEnum(boundedEnumMinute)($31)));
  });
  var boundedEnumMillisecond = new Data_Enum.BoundedEnum(function () {
      return boundedMillisecond;
  }, function () {
      return enumMillisecond;
  }, 1000, function (v) {
      return v;
  }, function (n) {
      if (n >= 0 && n <= 999) {
          return new Data_Maybe.Just(n);
      };
      if (Data_Boolean.otherwise) {
          return Data_Maybe.Nothing.value;
      };
      throw new Error("Failed pattern match at Data.Time.Component line 120, column 1 - line 120, column 59: " + [ n.constructor.name ]);
  });
  var enumMillisecond = new Data_Enum.Enum(function () {
      return ordMillisecond;
  }, function ($32) {
      return Data_Enum.toEnum(boundedEnumMillisecond)((function (v) {
          return v - 1 | 0;
      })(Data_Enum.fromEnum(boundedEnumMillisecond)($32)));
  }, function ($33) {
      return Data_Enum.toEnum(boundedEnumMillisecond)((function (v) {
          return v + 1 | 0;
      })(Data_Enum.fromEnum(boundedEnumMillisecond)($33)));
  });
  var boundedEnumHour = new Data_Enum.BoundedEnum(function () {
      return boundedHour;
  }, function () {
      return enumHour;
  }, 24, function (v) {
      return v;
  }, function (n) {
      if (n >= 0 && n <= 23) {
          return new Data_Maybe.Just(n);
      };
      if (Data_Boolean.otherwise) {
          return Data_Maybe.Nothing.value;
      };
      throw new Error("Failed pattern match at Data.Time.Component line 32, column 1 - line 32, column 45: " + [ n.constructor.name ]);
  });
  var enumHour = new Data_Enum.Enum(function () {
      return ordHour;
  }, function ($34) {
      return Data_Enum.toEnum(boundedEnumHour)((function (v) {
          return v - 1 | 0;
      })(Data_Enum.fromEnum(boundedEnumHour)($34)));
  }, function ($35) {
      return Data_Enum.toEnum(boundedEnumHour)((function (v) {
          return v + 1 | 0;
      })(Data_Enum.fromEnum(boundedEnumHour)($35)));
  });
  exports["ordHour"] = ordHour;
  exports["boundedHour"] = boundedHour;
  exports["enumHour"] = enumHour;
  exports["boundedEnumHour"] = boundedEnumHour;
  exports["ordMinute"] = ordMinute;
  exports["boundedMinute"] = boundedMinute;
  exports["enumMinute"] = enumMinute;
  exports["boundedEnumMinute"] = boundedEnumMinute;
  exports["ordSecond"] = ordSecond;
  exports["boundedSecond"] = boundedSecond;
  exports["enumSecond"] = enumSecond;
  exports["boundedEnumSecond"] = boundedEnumSecond;
  exports["ordMillisecond"] = ordMillisecond;
  exports["boundedMillisecond"] = boundedMillisecond;
  exports["enumMillisecond"] = enumMillisecond;
  exports["boundedEnumMillisecond"] = boundedEnumMillisecond;
})(PS["Data.Time.Component"] = PS["Data.Time.Component"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Apply = PS["Control.Apply"];
  var Data_Bounded = PS["Data.Bounded"];
  var Data_Enum = PS["Data.Enum"];
  var Data_Eq = PS["Data.Eq"];
  var Data_EuclideanRing = PS["Data.EuclideanRing"];
  var Data_Function = PS["Data.Function"];
  var Data_Functor = PS["Data.Functor"];
  var Data_HeytingAlgebra = PS["Data.HeytingAlgebra"];
  var Data_Int = PS["Data.Int"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Newtype = PS["Data.Newtype"];
  var Data_Ord = PS["Data.Ord"];
  var Data_Ordering = PS["Data.Ordering"];
  var Data_Ring = PS["Data.Ring"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Semiring = PS["Data.Semiring"];
  var Data_Show = PS["Data.Show"];
  var Data_Time_Component = PS["Data.Time.Component"];
  var Data_Time_Duration = PS["Data.Time.Duration"];
  var Data_Tuple = PS["Data.Tuple"];
  var $$Math = PS["Math"];
  var Partial_Unsafe = PS["Partial.Unsafe"];
  var Prelude = PS["Prelude"];                 
  var Time = (function () {
      function Time(value0, value1, value2, value3) {
          this.value0 = value0;
          this.value1 = value1;
          this.value2 = value2;
          this.value3 = value3;
      };
      Time.create = function (value0) {
          return function (value1) {
              return function (value2) {
                  return function (value3) {
                      return new Time(value0, value1, value2, value3);
                  };
              };
          };
      };
      return Time;
  })();
  var setSecond = function (s) {
      return function (v) {
          return new Time(v.value0, v.value1, s, v.value3);
      };
  };
  exports["Time"] = Time;
  exports["setSecond"] = setSecond;
})(PS["Data.Time"] = PS["Data.Time"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var UserDefined = (function () {
      function UserDefined(value0) {
          this.value0 = value0;
      };
      UserDefined.create = function (value0) {
          return new UserDefined(value0);
      };
      return UserDefined;
  })();
  exports["UserDefined"] = UserDefined;
})(PS["Game.Types.ActionName"] = PS["Game.Types.ActionName"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Data_Time = PS["Data.Time"];
  var Game_Types_ActionName = PS["Game.Types.ActionName"];                 
  var GameTimePassed = (function () {
      function GameTimePassed(value0) {
          this.value0 = value0;
      };
      GameTimePassed.create = function (value0) {
          return new GameTimePassed(value0);
      };
      return GameTimePassed;
  })();
  var Never = (function () {
      function Never() {

      };
      Never.value = new Never();
      return Never;
  })();
  var Always = (function () {
      function Always() {

      };
      Always.value = new Always();
      return Always;
  })();
  var FireStoked = (function () {
      function FireStoked() {

      };
      FireStoked.value = new FireStoked();
      return FireStoked;
  })();
  var ActionPerformed = (function () {
      function ActionPerformed(value0) {
          this.value0 = value0;
      };
      ActionPerformed.create = function (value0) {
          return new ActionPerformed(value0);
      };
      return ActionPerformed;
  })();
  var MilestoneReached = (function () {
      function MilestoneReached(value0) {
          this.value0 = value0;
      };
      MilestoneReached.create = function (value0) {
          return new MilestoneReached(value0);
      };
      return MilestoneReached;
  })();
  var TimeSinceMilestone = (function () {
      function TimeSinceMilestone(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      TimeSinceMilestone.create = function (value0) {
          return function (value1) {
              return new TimeSinceMilestone(value0, value1);
          };
      };
      return TimeSinceMilestone;
  })();
  var MilestoneAtCount = (function () {
      function MilestoneAtCount(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      MilestoneAtCount.create = function (value0) {
          return function (value1) {
              return new MilestoneAtCount(value0, value1);
          };
      };
      return MilestoneAtCount;
  })();
  var MilestoneGreaterThan = (function () {
      function MilestoneGreaterThan(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      MilestoneGreaterThan.create = function (value0) {
          return function (value1) {
              return new MilestoneGreaterThan(value0, value1);
          };
      };
      return MilestoneGreaterThan;
  })();
  var Pure = (function () {
      function Pure(value0) {
          this.value0 = value0;
      };
      Pure.create = function (value0) {
          return new Pure(value0);
      };
      return Pure;
  })();
  var And = (function () {
      function And(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      And.create = function (value0) {
          return function (value1) {
              return new And(value0, value1);
          };
      };
      return And;
  })();
  exports["Pure"] = Pure;
  exports["And"] = And;
  exports["GameTimePassed"] = GameTimePassed;
  exports["Never"] = Never;
  exports["Always"] = Always;
  exports["FireStoked"] = FireStoked;
  exports["ActionPerformed"] = ActionPerformed;
  exports["MilestoneReached"] = MilestoneReached;
  exports["TimeSinceMilestone"] = TimeSinceMilestone;
  exports["MilestoneAtCount"] = MilestoneAtCount;
  exports["MilestoneGreaterThan"] = MilestoneGreaterThan;
})(PS["Game.Types.Condition"] = PS["Game.Types.Condition"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Data_Show = PS["Data.Show"];
  var Game_Types_ActionName = PS["Game.Types.ActionName"];
  var Prelude = PS["Prelude"];
  var AddToResource = (function () {
      function AddToResource(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      AddToResource.create = function (value0) {
          return function (value1) {
              return new AddToResource(value0, value1);
          };
      };
      return AddToResource;
  })();
  var SetMilestoneReached = (function () {
      function SetMilestoneReached(value0) {
          this.value0 = value0;
      };
      SetMilestoneReached.create = function (value0) {
          return new SetMilestoneReached(value0);
      };
      return SetMilestoneReached;
  })();
  var IncrementMilestone = (function () {
      function IncrementMilestone(value0) {
          this.value0 = value0;
      };
      IncrementMilestone.create = function (value0) {
          return new IncrementMilestone(value0);
      };
      return IncrementMilestone;
  })();
  var ActivateAction = (function () {
      function ActivateAction(value0) {
          this.value0 = value0;
      };
      ActivateAction.create = function (value0) {
          return new ActivateAction(value0);
      };
      return ActivateAction;
  })();
  var GameOver = (function () {
      function GameOver() {

      };
      GameOver.value = new GameOver();
      return GameOver;
  })();
  var showEffect = new Data_Show.Show(function (e) {
      return "(some effect)";
  });
  exports["AddToResource"] = AddToResource;
  exports["SetMilestoneReached"] = SetMilestoneReached;
  exports["IncrementMilestone"] = IncrementMilestone;
  exports["ActivateAction"] = ActivateAction;
  exports["GameOver"] = GameOver;
  exports["showEffect"] = showEffect;
})(PS["Game.Types.Effect"] = PS["Game.Types.Effect"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Data_List = PS["Data.List"];
  var Data_List_Types = PS["Data.List.Types"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Show = PS["Data.Show"];
  var Data_Tuple = PS["Data.Tuple"];
  var Game_Types_Condition = PS["Game.Types.Condition"];
  var Game_Types_Effect = PS["Game.Types.Effect"];
  var Prelude = PS["Prelude"];                 
  var Narration = (function () {
      function Narration(value0) {
          this.value0 = value0;
      };
      Narration.create = function (value0) {
          return new Narration(value0);
      };
      return Narration;
  })();
  var Dialogue = (function () {
      function Dialogue(value0) {
          this.value0 = value0;
      };
      Dialogue.create = function (value0) {
          return new Dialogue(value0);
      };
      return Dialogue;
  })();
  var StartInteraction = (function () {
      function StartInteraction() {

      };
      StartInteraction.value = new StartInteraction();
      return StartInteraction;
  })();
  var EndInteraction = (function () {
      function EndInteraction() {

      };
      EndInteraction.value = new EndInteraction();
      return EndInteraction;
  })();
  var Goto = (function () {
      function Goto(value0) {
          this.value0 = value0;
      };
      Goto.create = function (value0) {
          return new Goto(value0);
      };
      return Goto;
  })();
  var Effectful = (function () {
      function Effectful(value0) {
          this.value0 = value0;
      };
      Effectful.create = function (value0) {
          return new Effectful(value0);
      };
      return Effectful;
  })();
  var Atomic = (function () {
      function Atomic(value0) {
          this.value0 = value0;
      };
      Atomic.create = function (value0) {
          return new Atomic(value0);
      };
      return Atomic;
  })();
  var Sequenced = (function () {
      function Sequenced(value0) {
          this.value0 = value0;
      };
      Sequenced.create = function (value0) {
          return new Sequenced(value0);
      };
      return Sequenced;
  })();
  var PlayerChoice = (function () {
      function PlayerChoice(value0) {
          this.value0 = value0;
      };
      PlayerChoice.create = function (value0) {
          return new PlayerChoice(value0);
      };
      return PlayerChoice;
  })();
  var Conditioned = (function () {
      function Conditioned(value0) {
          this.value0 = value0;
      };
      Conditioned.create = function (value0) {
          return new Conditioned(value0);
      };
      return Conditioned;
  })();
  var Random = (function () {
      function Random(value0) {
          this.value0 = value0;
      };
      Random.create = function (value0) {
          return new Random(value0);
      };
      return Random;
  })();
  var Cases = (function () {
      function Cases(value0) {
          this.value0 = value0;
      };
      Cases.create = function (value0) {
          return new Cases(value0);
      };
      return Cases;
  })();
  var Choice = (function () {
      function Choice(value0) {
          this.value0 = value0;
      };
      Choice.create = function (value0) {
          return new Choice(value0);
      };
      return Choice;
  })();
  var ConditionedEvent = (function () {
      function ConditionedEvent(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      ConditionedEvent.create = function (value0) {
          return function (value1) {
              return new ConditionedEvent(value0, value1);
          };
      };
      return ConditionedEvent;
  })();
  var showStoryEvent = new Data_Show.Show(function (e) {
      if (e instanceof Atomic && e.value0 instanceof StartInteraction) {
          return "start-interaction";
      };
      if (e instanceof Atomic && e.value0 instanceof EndInteraction) {
          return "end-interaction";
      };
      if (e instanceof Atomic && e.value0 instanceof Narration) {
          return "ln: " + e.value0.value0;
      };
      if (e instanceof Atomic && e.value0 instanceof Dialogue) {
          return "di: " + e.value0.value0;
      };
      if (e instanceof Atomic && e.value0 instanceof Effectful) {
          return "effect: " + Data_Show.show(Game_Types_Effect.showEffect)(e.value0.value0);
      };
      if (e instanceof Atomic && e.value0 instanceof Goto) {
          return "goto: " + e.value0.value0;
      };
      if (e instanceof Conditioned) {
          return "conditioned: " + Data_Show.show(showStoryEvent)(e.value0.value1);
      };
      if (e instanceof Sequenced) {
          return Data_Show.show(Data_List_Types.showList(showStoryEvent))(e.value0);
      };
      return "unimplemented";
  });
  exports["Atomic"] = Atomic;
  exports["Sequenced"] = Sequenced;
  exports["PlayerChoice"] = PlayerChoice;
  exports["Conditioned"] = Conditioned;
  exports["Random"] = Random;
  exports["Cases"] = Cases;
  exports["ConditionedEvent"] = ConditionedEvent;
  exports["Narration"] = Narration;
  exports["Dialogue"] = Dialogue;
  exports["StartInteraction"] = StartInteraction;
  exports["EndInteraction"] = EndInteraction;
  exports["Goto"] = Goto;
  exports["Effectful"] = Effectful;
  exports["Choice"] = Choice;
  exports["showStoryEvent"] = showStoryEvent;
})(PS["Game.Types.StoryEvent"] = PS["Game.Types.StoryEvent"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Data_List = PS["Data.List"];
  var Data_List_Types = PS["Data.List.Types"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Show = PS["Data.Show"];
  var Game_Types_Condition = PS["Game.Types.Condition"];
  var Game_Types_StoryEvent = PS["Game.Types.StoryEvent"];
  var Prelude = PS["Prelude"];                 
  var TopLevel = (function () {
      function TopLevel(value0) {
          this.value0 = value0;
      };
      TopLevel.create = function (value0) {
          return new TopLevel(value0);
      };
      return TopLevel;
  })();
  var trigger = function (c) {
      return function (v) {
          return new TopLevel({
              name: v.value0.name,
              reoccurring: v.value0.reoccurring,
              trigger: c,
              event: v.value0.event
          });
      };
  };
  var showTopLevelEvent = new Data_Show.Show(function (v) {
      return Data_Show.show(Data_Show.showString)(v.value0.name) + (" " + Data_Show.show(Game_Types_StoryEvent.showStoryEvent)(v.value0.event));
  });
  var reoccurring = function (v) {
      return new TopLevel({
          name: v.value0.name,
          reoccurring: true,
          trigger: v.value0.trigger,
          event: v.value0.event
      });
  };
  var $$new = function (n) {
      return new TopLevel({
          name: n,
          reoccurring: false,
          trigger: new Game_Types_Condition.Pure(Game_Types_Condition.Never.value),
          event: new Game_Types_StoryEvent.Sequenced(Data_List_Types.Nil.value)
      });
  };
  var body = function (e) {
      return function (v) {
          return new TopLevel({
              name: v.value0.name,
              reoccurring: v.value0.reoccurring,
              trigger: v.value0.trigger,
              event: e
          });
      };
  };
  exports["TopLevel"] = TopLevel;
  exports["new"] = $$new;
  exports["reoccurring"] = reoccurring;
  exports["trigger"] = trigger;
  exports["body"] = body;
  exports["showTopLevelEvent"] = showTopLevelEvent;
})(PS["Game.Types.TopLevelEvent"] = PS["Game.Types.TopLevelEvent"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Show = PS["Data.Show"];
  var Game_Types_TopLevelEvent = PS["Game.Types.TopLevelEvent"];
  var Prelude = PS["Prelude"];                 
  var Story = (function () {
      function Story(value0) {
          this.value0 = value0;
      };
      Story.create = function (value0) {
          return new Story(value0);
      };
      return Story;
  })();
  var showStory = new Data_Show.Show(function (v) {
      return "Story: \x0a" + Data_Show.show(Data_Show.showArray(Game_Types_TopLevelEvent.showTopLevelEvent))(v.value0);
  });
  var semigroupStory = new Data_Semigroup.Semigroup(function (v) {
      return function (v1) {
          return new Story(Data_Semigroup.append(Data_Semigroup.semigroupArray)(v.value0)(v1.value0));
      };
  });
  var monoidStory = new Data_Monoid.Monoid(function () {
      return semigroupStory;
  }, new Story([  ]));
  exports["Story"] = Story;
  exports["showStory"] = showStory;
  exports["semigroupStory"] = semigroupStory;
  exports["monoidStory"] = monoidStory;
})(PS["Game.Types.Story"] = PS["Game.Types.Story"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Data_List = PS["Data.List"];
  var Data_List_Types = PS["Data.List.Types"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Game_Types_Story = PS["Game.Types.Story"];
  var Game_Types_StoryEvent = PS["Game.Types.StoryEvent"];
  var Prelude = PS["Prelude"];                 
  var Buildable = function (combine, $$default) {
      this.combine = combine;
      this["default"] = $$default;
  };
  var $$default = function (dict) {
      return dict["default"];
  };
  var combine = function (dict) {
      return dict.combine;
  };
  var buildableStoryEvent = new Buildable(function (v) {
      return function (v1) {
          if (v instanceof Game_Types_StoryEvent.Sequenced && v1 instanceof Game_Types_StoryEvent.Sequenced) {
              return new Game_Types_StoryEvent.Sequenced(Data_Semigroup.append(Data_List_Types.semigroupList)(v.value0)(v1.value0));
          };
          if (v instanceof Game_Types_StoryEvent.Sequenced) {
              return new Game_Types_StoryEvent.Sequenced(Data_List.snoc(v.value0)(v1));
          };
          if (v1 instanceof Game_Types_StoryEvent.Sequenced) {
              return new Game_Types_StoryEvent.Sequenced(new Data_List_Types.Cons(v, v1.value0));
          };
          return new Game_Types_StoryEvent.Sequenced(new Data_List_Types.Cons(v, new Data_List_Types.Cons(v1, Data_List_Types.Nil.value)));
      };
  }, new Game_Types_StoryEvent.Sequenced(Data_List_Types.Nil.value));
  var buildableStory = new Buildable(Data_Semigroup.append(Game_Types_Story.semigroupStory), Data_Monoid.mempty(Game_Types_Story.monoidStory));
  var buildableList = new Buildable(Data_Semigroup.append(Data_List_Types.semigroupList), Data_List_Types.Nil.value);
  exports["combine"] = combine;
  exports["Buildable"] = Buildable;
  exports["buildableStory"] = buildableStory;
  exports["buildableStoryEvent"] = buildableStoryEvent;
  exports["buildableList"] = buildableList;
})(PS["Script.Buildable"] = PS["Script.Buildable"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Applicative = PS["Control.Applicative"];
  var Control_Apply = PS["Control.Apply"];
  var Control_Bind = PS["Control.Bind"];
  var Control_Monad = PS["Control.Monad"];
  var Data_Functor = PS["Data.Functor"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Show = PS["Data.Show"];
  var Prelude = PS["Prelude"];
  var Script_Buildable = PS["Script.Buildable"];                 
  var BD = (function () {
      function BD(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      BD.create = function (value0) {
          return function (value1) {
              return new BD(value0, value1);
          };
      };
      return BD;
  })();
  var getConstruct = function (v) {
      return v.value0;
  };
  var bFunctor = function (dictBuildable) {
      return new Data_Functor.Functor(function (f) {
          return function (v) {
              return new BD(v.value0, f(v.value1));
          };
      });
  };
  var bApply = function (dictBuildable) {
      return new Control_Apply.Apply(function () {
          return bFunctor(dictBuildable);
      }, function (v) {
          return function (v1) {
              return new BD(Script_Buildable.combine(dictBuildable)(v.value0)(v1.value0), v.value1(v1.value1));
          };
      });
  };
  var sBind = function (dictBuildable) {
      return new Control_Bind.Bind(function () {
          return bApply(dictBuildable);
      }, function (v) {
          return function (fn) {
              var v1 = fn(v.value1);
              return new BD(Script_Buildable.combine(dictBuildable)(v.value0)(v1.value0), v1.value1);
          };
      });
  };
  exports["BD"] = BD;
  exports["getConstruct"] = getConstruct;
  exports["bFunctor"] = bFunctor;
  exports["bApply"] = bApply;
  exports["sBind"] = sBind;
})(PS["Script.Builder"] = PS["Script.Builder"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Common_Annex = PS["Common.Annex"];
  var Control_Category = PS["Control.Category"];
  var Control_Semigroupoid = PS["Control.Semigroupoid"];
  var Data_Enum = PS["Data.Enum"];
  var Data_Function = PS["Data.Function"];
  var Data_List = PS["Data.List"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Time = PS["Data.Time"];
  var Data_Time_Component = PS["Data.Time.Component"];
  var Data_Tuple = PS["Data.Tuple"];
  var Data_Unit = PS["Data.Unit"];
  var Game_Types_ActionName = PS["Game.Types.ActionName"];
  var Game_Types_Condition = PS["Game.Types.Condition"];
  var Game_Types_Effect = PS["Game.Types.Effect"];
  var Game_Types_Story = PS["Game.Types.Story"];
  var Game_Types_StoryEvent = PS["Game.Types.StoryEvent"];
  var Game_Types_TopLevelEvent = PS["Game.Types.TopLevelEvent"];
  var Partial_Unsafe = PS["Partial.Unsafe"];
  var Prelude = PS["Prelude"];
  var Script_Buildable = PS["Script.Buildable"];
  var Script_Builder = PS["Script.Builder"];                 
  var unconditionally = Common_Annex.pipeForward(Game_Types_Condition.Always.value)(Game_Types_Condition.Pure.create);
  var timeSinceMilestone = function (t) {
      return function (c) {
          return new Game_Types_Condition.Pure(new Game_Types_Condition.TimeSinceMilestone(t, c));
      };
  };
  var reoccuringWhen = true;              
  var occursOnceWhen = false;                 
  var never = Common_Annex.pipeForward(Game_Types_Condition.Never.value)(Game_Types_Condition.Pure.create);
  var nestBuilder = function (fn) {
      return function (bd) {
          return fn(Script_Builder.getConstruct(bd));
      };
  };
  var milestoneReached = function ($5) {
      return Game_Types_Condition.Pure.create(Game_Types_Condition.MilestoneReached.create($5));
  };
  var milestoneGreaterThan = function (m) {
      return function (c) {
          return new Game_Types_Condition.Pure(new Game_Types_Condition.MilestoneGreaterThan(m, c));
      };
  };
  var milestoneAtCount = function (m) {
      return function (c) {
          return new Game_Types_Condition.Pure(new Game_Types_Condition.MilestoneAtCount(m, c));
      };
  };
  var gameTimePassed = function ($6) {
      return Game_Types_Condition.Pure.create(Game_Types_Condition.GameTimePassed.create($6));
  };
  var fireStoked = Common_Annex.pipeForward(Game_Types_Condition.FireStoked.value)(Game_Types_Condition.Pure.create);            
  var comp = function (dictBoundedEnum) {
      return function (x) {
          return Data_Maybe.fromJust()(Data_Enum.toEnum(dictBoundedEnum)(x));
      };
  };
  var zeroTime = new Data_Time.Time(comp(Data_Time_Component.boundedEnumHour)(0), comp(Data_Time_Component.boundedEnumMinute)(0), comp(Data_Time_Component.boundedEnumSecond)(0), comp(Data_Time_Component.boundedEnumMillisecond)(0));
  var seconds = function (x) {
      return Data_Time.setSecond(comp(Data_Time_Component.boundedEnumSecond)(x))(zeroTime);
  };                                              
  var build = function (dictBuildable) {
      return function (x) {
          return new Script_Builder.BD(x, Data_Unit.unit);
      };
  };
  var cases = function (es) {
      return build(Script_Buildable.buildableStoryEvent)(new Game_Types_StoryEvent.Cases(es));
  };
  var choices = function (c) {
      return build(Script_Buildable.buildableStoryEvent)(new Game_Types_StoryEvent.PlayerChoice(c));
  };
  var cond = function (c) {
      return function (e) {
          return build(Script_Buildable.buildableStoryEvent)(new Game_Types_StoryEvent.Conditioned(new Game_Types_StoryEvent.ConditionedEvent(c, e)));
      };
  };
  var di = function (text) {
      return build(Script_Buildable.buildableStoryEvent)(new Game_Types_StoryEvent.Atomic(new Game_Types_StoryEvent.Dialogue(text)));
  };
  var effect = function (e) {
      return build(Script_Buildable.buildableStoryEvent)(new Game_Types_StoryEvent.Atomic(new Game_Types_StoryEvent.Effectful(e)));
  };
  var $$goto = function (s) {
      return build(Script_Buildable.buildableStoryEvent)(new Game_Types_StoryEvent.Atomic(new Game_Types_StoryEvent.Goto(s)));
  };
  var ln = function (text) {
      return build(Script_Buildable.buildableStoryEvent)(new Game_Types_StoryEvent.Atomic(new Game_Types_StoryEvent.Narration(text)));
  };
  var makeTopLevel = function (n) {
      return function (r) {
          return function (c) {
              return function (e) {
                  var tl = Common_Annex.pipeForward(Common_Annex.pipeForward(Common_Annex.pipeForward(Game_Types_TopLevelEvent["new"](n))((function () {
                      if (r) {
                          return Game_Types_TopLevelEvent.reoccurring;
                      };
                      return Control_Category.identity(Control_Category.categoryFn);
                  })()))(Game_Types_TopLevelEvent.trigger(c)))(Game_Types_TopLevelEvent.body(e));
                  return build(Script_Buildable.buildableStory)(new Game_Types_Story.Story([ tl ]));
              };
          };
      };
  };
  var named = function (n) {
      return makeTopLevel(n)(false)(never);
  };
  var top = makeTopLevel("");
  var prompt = function (s) {
      return function (e) {
          return build(Script_Buildable.buildableList)(Data_List.singleton(new Game_Types_StoryEvent.Choice({
              prompt: s,
              consq: e,
              condition: unconditionally
          })));
      };
  };
  var rand = function (es) {
      return build(Script_Buildable.buildableStoryEvent)(new Game_Types_StoryEvent.Random(es));
  };
  var restrict = build(Script_Buildable.buildableStoryEvent)(new Game_Types_StoryEvent.Atomic(Game_Types_StoryEvent.StartInteraction.value));
  var resume = build(Script_Buildable.buildableStoryEvent)(new Game_Types_StoryEvent.Atomic(Game_Types_StoryEvent.EndInteraction.value));
  var unweighted = function (e) {
      return build(Script_Buildable.buildableList)(Data_List.singleton(new Data_Tuple.Tuple(e, 1)));
  };
  var weighted = function (w) {
      return function (e) {
          return build(Script_Buildable.buildableList)(Data_List.singleton(new Data_Tuple.Tuple(e, w)));
      };
  };
  var when = function (c) {
      return function (e) {
          return build(Script_Buildable.buildableList)(Data_List.singleton(new Game_Types_StoryEvent.ConditionedEvent(c, e)));
      };
  };
  var begin = Script_Builder.getConstruct;
  var and = Game_Types_Condition.And.create;
  var activateAction = function ($7) {
      return Game_Types_Effect.ActivateAction.create(Game_Types_ActionName.UserDefined.create($7));
  };
  var actionPerformed = function ($8) {
      return Game_Types_Condition.Pure.create(Game_Types_Condition.ActionPerformed.create(Game_Types_ActionName.UserDefined.create($8)));
  };
  exports["begin"] = begin;
  exports["build"] = build;
  exports["nestBuilder"] = nestBuilder;
  exports["reoccuringWhen"] = reoccuringWhen;
  exports["occursOnceWhen"] = occursOnceWhen;
  exports["makeTopLevel"] = makeTopLevel;
  exports["top"] = top;
  exports["named"] = named;
  exports["ln"] = ln;
  exports["di"] = di;
  exports["restrict"] = restrict;
  exports["resume"] = resume;
  exports["cond"] = cond;
  exports["effect"] = effect;
  exports["goto"] = $$goto;
  exports["choices"] = choices;
  exports["prompt"] = prompt;
  exports["cases"] = cases;
  exports["when"] = when;
  exports["rand"] = rand;
  exports["unweighted"] = unweighted;
  exports["weighted"] = weighted;
  exports["and"] = and;
  exports["gameTimePassed"] = gameTimePassed;
  exports["never"] = never;
  exports["unconditionally"] = unconditionally;
  exports["fireStoked"] = fireStoked;
  exports["actionPerformed"] = actionPerformed;
  exports["milestoneReached"] = milestoneReached;
  exports["timeSinceMilestone"] = timeSinceMilestone;
  exports["milestoneAtCount"] = milestoneAtCount;
  exports["milestoneGreaterThan"] = milestoneGreaterThan;
  exports["activateAction"] = activateAction;
  exports["comp"] = comp;
  exports["zeroTime"] = zeroTime;
  exports["seconds"] = seconds;
})(PS["Script.Keywords"] = PS["Script.Keywords"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Control_Bind = PS["Control.Bind"];
  var Data_Show = PS["Data.Show"];
  var Game_Types_Effect = PS["Game.Types.Effect"];
  var Game_Types_Story = PS["Game.Types.Story"];
  var Prelude = PS["Prelude"];
  var Script_Buildable = PS["Script.Buildable"];
  var Script_Builder = PS["Script.Builder"];
  var Script_Keywords = PS["Script.Keywords"];                 
  var story = Script_Keywords.begin(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStory))(Script_Keywords.nestBuilder(Script_Keywords.top(Script_Keywords.occursOnceWhen)(Script_Keywords.gameTimePassed(Script_Keywords.seconds(2))))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("The room is cold."))(function () {
      return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("Foul water drips from the ceiling."))(function () {
          return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("..."))(function () {
              return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("You shiver."))(function () {
                  return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.nestBuilder(Script_Keywords.choices)(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableList))(Script_Keywords.nestBuilder(Script_Keywords.prompt("meditate"))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("You breathe deeply."))(function () {
                      return Script_Keywords.ln("The freezing air bites your face.");
                  })))(function () {
                      return Script_Keywords.nestBuilder(Script_Keywords.prompt("look up"))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("A thick haze clouds your vision."))(function () {
                          return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("But pale white letters speak to you..."))(function () {
                              return Script_Keywords.ln("FUMIGATION CHAMBER");
                          });
                      }));
                  })))(function () {
                      return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("..."))(function () {
                          return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("The cold is unbearable."))(function () {
                              return Script_Keywords.effect(Script_Keywords.activateAction("search for wood"));
                          });
                      });
                  });
              });
          });
      });
  })))(function () {
      return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStory))(Script_Keywords.nestBuilder(Script_Keywords.top(Script_Keywords.occursOnceWhen)(Script_Keywords.and(Script_Keywords.actionPerformed("search for wood"))(Script_Keywords.milestoneAtCount("wood-searched")(1))))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("The ground is covered in grass..."))(function () {
          return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("And dry little twigs."))(function () {
              return Script_Keywords.ln("They're meager, but they'll feed a fire.");
          });
      })))(function () {
          return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStory))(Script_Keywords.nestBuilder(Script_Keywords.top(Script_Keywords.occursOnceWhen)(Script_Keywords.fireStoked))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("Embers hatch in the brush."))(function () {
              return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("You hover your hands over the flame."))(function () {
                  return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("..."))(function () {
                      return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("The fire is roaring."))(function () {
                          return Script_Keywords.effect(new Game_Types_Effect.IncrementMilestone("fire-stoked"));
                      });
                  });
              });
          })))(function () {
              return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStory))(Script_Keywords.nestBuilder(Script_Keywords.top(Script_Keywords.occursOnceWhen)(Script_Keywords.and(Script_Keywords.fireStoked)(Script_Keywords.milestoneAtCount("fire-stoked")(1))))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("You bring your face close to the flames."))(function () {
                  return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("A foreign smile stretches your lips."))(function () {
                      return Script_Keywords.effect(new Game_Types_Effect.IncrementMilestone("fire-stoked"));
                  });
              })))(function () {
                  return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStory))(Script_Keywords.nestBuilder(Script_Keywords.top(Script_Keywords.reoccuringWhen)(Script_Keywords.and(Script_Keywords.fireStoked)(Script_Keywords.milestoneGreaterThan("fire-stoked")(1))))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.nestBuilder(Script_Keywords.rand)(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableList))(Script_Keywords.nestBuilder(Script_Keywords.weighted(4))(Script_Keywords.ln("The fire is roaring.")))(function () {
                      return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableList))(Script_Keywords.nestBuilder(Script_Keywords.unweighted)(Script_Keywords.ln("The flames double in height.")))(function () {
                          return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableList))(Script_Keywords.nestBuilder(Script_Keywords.unweighted)(Script_Keywords.ln("The fire crackles with a human voice.")))(function () {
                              return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableList))(Script_Keywords.nestBuilder(Script_Keywords.unweighted)(Script_Keywords.ln("You shiver with warmth.")))(function () {
                                  return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableList))(Script_Keywords.nestBuilder(Script_Keywords.unweighted)(Script_Keywords.ln("The flames rise.")))(function () {
                                      return Script_Keywords.nestBuilder(Script_Keywords.unweighted)(Script_Keywords.ln("The fire dances with primitive urgency."));
                                  });
                              });
                          });
                      });
                  })))(function () {
                      return Script_Keywords.effect(new Game_Types_Effect.IncrementMilestone("fire-stoked"));
                  })))(function () {
                      return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStory))(Script_Keywords.nestBuilder(Script_Keywords.top(Script_Keywords.occursOnceWhen)(Script_Keywords.milestoneAtCount("wood-searched")(2)))(Script_Keywords.ln("The false starlight illuminates a rotting log.")))(function () {
                          return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStory))(Script_Keywords.nestBuilder(Script_Keywords.top(Script_Keywords.reoccuringWhen)(Script_Keywords.and(Script_Keywords.milestoneGreaterThan("wood-searched")(2))(Script_Keywords.actionPerformed("search for wood"))))(Script_Keywords.nestBuilder(Script_Keywords.rand)(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableList))(Script_Keywords.nestBuilder(Script_Keywords.unweighted)(Script_Keywords.ln("A few more twigs for the fire...")))(function () {
                              return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableList))(Script_Keywords.nestBuilder(Script_Keywords.unweighted)(Script_Keywords.ln("The twigs are dirty, but dry enough...")))(function () {
                                  return Script_Keywords.nestBuilder(Script_Keywords.unweighted)(Script_Keywords.ln("From your dark wandering you return with a small bounty..."));
                              });
                          }))))(function () {
                              return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStory))(Script_Keywords.nestBuilder(Script_Keywords.top(Script_Keywords.occursOnceWhen)(Script_Keywords.timeSinceMilestone("fire-stoked")(Script_Keywords.seconds(5))))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("..."))(function () {
                                  return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("There is something artificial about this place."))(function () {
                                      return Script_Keywords.effect(Script_Keywords.activateAction("investigate"));
                                  });
                              })))(function () {
                                  return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStory))(Script_Keywords.nestBuilder(Script_Keywords.top(Script_Keywords.occursOnceWhen)(Script_Keywords.milestoneAtCount("did-investigate")(1)))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("The grass seems to stretch on for miles..."))(function () {
                                      return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.restrict)(function () {
                                          return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("And the stars look false."))(function () {
                                              return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.nestBuilder(Script_Keywords.choices)(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableList))(Script_Keywords.nestBuilder(Script_Keywords.prompt("call out"))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("Your own voice returns to you from every direction..."))(function () {
                                                  return Script_Keywords.ln("Even from above.");
                                              })))(function () {
                                                  return Script_Keywords.nestBuilder(Script_Keywords.prompt("stay silent"))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("The haze congeals on your face..."))(function () {
                                                      return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("But your eyes see better in silence."))(function () {
                                                          return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("The haze hangs heavily over the surrounding forest."))(function () {
                                                              return Script_Keywords.ln("You return to the fire.");
                                                          });
                                                      });
                                                  }));
                                              })))(function () {
                                                  return Script_Keywords.resume;
                                              });
                                          });
                                      });
                                  })))(function () {
                                      return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStory))(Script_Keywords.nestBuilder(Script_Keywords.top(Script_Keywords.occursOnceWhen)(Script_Keywords.milestoneAtCount("did-investigate")(2)))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.restrict)(function () {
                                          return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("You find a body lying in the grass."))(function () {
                                              return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("It's not moving."))(function () {
                                                  return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("The mud-stained dress on its back is speckled with flowers."))(function () {
                                                      return Script_Keywords.nestBuilder(Script_Keywords.choices)(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableList))(Script_Keywords.nestBuilder(Script_Keywords.prompt("turn it over"))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("A skull stares back up at you, framed by long blonde hair."))(function () {
                                                          return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("Its teeth are small and rotted."))(function () {
                                                              return Script_Keywords["goto"]("defile-corpse-choice");
                                                          });
                                                      })))(function () {
                                                          return Script_Keywords.nestBuilder(Script_Keywords.prompt("crush its neck"))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("Its bony blonde head snaps from its shoulders..."))(function () {
                                                              return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("And rolls into the grass."))(function () {
                                                                  return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("..."))(function () {
                                                                      return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.effect(new Game_Types_Effect.SetMilestoneReached("corpse-defiled")))(function () {
                                                                          return Script_Keywords["goto"]("defile-corpse-choice");
                                                                      });
                                                                  });
                                                              });
                                                          }));
                                                      }));
                                                  });
                                              });
                                          });
                                      })))(function () {
                                          return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStory))(Script_Keywords.nestBuilder(Script_Keywords.named("defile-corpse-choice"))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("Your hunger demands compense."))(function () {
                                              return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.nestBuilder(Script_Keywords.choices)(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableList))(Script_Keywords.nestBuilder(Script_Keywords.prompt("search body"))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("You rip off the corpse's dress..."))(function () {
                                                  return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("But only find an insect den among its fleshy bones."))(function () {
                                                      return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("There is nothing of value here."))(function () {
                                                          return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("Except the dress."))(function () {
                                                              return Script_Keywords.effect(new Game_Types_Effect.SetMilestoneReached("corpse-dress-taken"));
                                                          });
                                                      });
                                                  });
                                              })))(function () {
                                                  return Script_Keywords.nestBuilder(Script_Keywords.prompt("return to fire"))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("You leave the weeping skull be."))(function () {
                                                      return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("The body fades into the haze..."))(function () {
                                                          return Script_Keywords.ln("But not your memory of its flowery dress.");
                                                      });
                                                  }));
                                              })))(function () {
                                                  return Script_Keywords.resume;
                                              });
                                          })))(function () {
                                              return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStory))(Script_Keywords.nestBuilder(Script_Keywords.top(Script_Keywords.occursOnceWhen)(Script_Keywords.milestoneAtCount("did-investigate")(3)))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.restrict)(function () {
                                                  return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("It's raining..."))(function () {
                                                      return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("The drops sting your body."))(function () {
                                                          return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("You go back inside."))(function () {
                                                              return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("There is a someone sitting by the fire."))(function () {
                                                                  return Script_Keywords.nestBuilder(Script_Keywords.choices)(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableList))(Script_Keywords.nestBuilder(Script_Keywords.prompt("Who are you?"))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("..."))(function () {
                                                                      return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("The man looks up."))(function () {
                                                                          return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.di("Didn't expect to ever find another soul up here on AL 50."))(function () {
                                                                              return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.di("Except for ol' Cathy."))(function () {
                                                                                  return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.nestBuilder(Script_Keywords.cond(Script_Keywords.milestoneReached("corpse-dress-taken")))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("...whose dress I see you've taken to wearing."))(function () {
                                                                                      return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.di("An original look, I can give you that."))(function () {
                                                                                          return Script_Keywords.ln("The man chuckles to himself.");
                                                                                      });
                                                                                  })))(function () {
                                                                                      return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.nestBuilder(Script_Keywords.cond(Script_Keywords.milestoneReached("corpse-defiled")))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("Poor girl's head came right off her poor head."))(function () {
                                                                                          return Script_Keywords.di("Wonder what kind of nasty critter would do something like that...");
                                                                                      })))(function () {
                                                                                          return Script_Keywords["goto"]("visitor-intro");
                                                                                      });
                                                                                  });
                                                                              });
                                                                          });
                                                                      });
                                                                  })))(function () {
                                                                      return Script_Keywords.nestBuilder(Script_Keywords.prompt("Get out!"))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("..."))(function () {
                                                                          return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("The man is unfazed."))(function () {
                                                                              return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.di("You ought to relax, stranger."))(function () {
                                                                                  return Script_Keywords.nestBuilder(Script_Keywords.cases)(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableList))(Script_Keywords.nestBuilder(Script_Keywords.when(Script_Keywords.milestoneReached("corpse-dress-taken")))(Script_Keywords.ln("I ain't afraid of a haggard man in a flowery dress.")))(function () {
                                                                                      return Script_Keywords.nestBuilder(Script_Keywords.when(Script_Keywords.milestoneReached("corpse-defiled")))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("You aren't going to be able to crush my bony head like you did poor Cathy's."))(function () {
                                                                                          return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.di("Ain't nobody up here on AL 50 except me..."))(function () {
                                                                                              return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.di("And you."))(function () {
                                                                                                  return Script_Keywords["goto"]("visitor-intro");
                                                                                              });
                                                                                          });
                                                                                      }));
                                                                                  }));
                                                                              });
                                                                          });
                                                                      }));
                                                                  }));
                                                              });
                                                          });
                                                      });
                                                  });
                                              })))(function () {
                                                  return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStory))(Script_Keywords.nestBuilder(Script_Keywords.named("visitor-intro"))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("The man reaches out his hand."))(function () {
                                                      return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("You shake it."))(function () {
                                                          return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.di("You look like you need some food, friend."))(function () {
                                                              return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.di("Have a critter."))(function () {
                                                                  return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("The man plops a dead rat into your trembling palm."))(function () {
                                                                      return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.effect(new Game_Types_Effect.AddToResource("rats", 1)))(function () {
                                                                          return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.di("I tell you I never seen rats on the whole Ark like I seen 'em here."))(function () {
                                                                              return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.di("Name's Don."))(function () {
                                                                                  return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.resume)(function () {
                                                                                      return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.di("Mine, not the rat's."))(function () {
                                                                                          return Script_Keywords.effect(Script_Keywords.activateAction("hunt rats"));
                                                                                      });
                                                                                  });
                                                                              });
                                                                          });
                                                                      });
                                                                  });
                                                              });
                                                          });
                                                      });
                                                  })))(function () {
                                                      return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStory))(Script_Keywords.nestBuilder(Script_Keywords.top(Script_Keywords.occursOnceWhen)(Script_Keywords.milestoneAtCount("rats-hunted")(1)))(Script_Keywords.ln("You scramble in the mud and dig your nails into a writhing mass.")))(function () {
                                                          return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStory))(Script_Keywords.nestBuilder(Script_Keywords.top(Script_Keywords.occursOnceWhen)(Script_Keywords.timeSinceMilestone("rats-hunted")(Script_Keywords.seconds(10))))(Script_Keywords["goto"]("game-over")))(function () {
                                                              return Script_Keywords.nestBuilder(Script_Keywords.named("game-over"))(Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln("..."))(function () {
                                                                  return Control_Bind.discard(Control_Bind.discardUnit)(Script_Builder.sBind(Script_Buildable.buildableStoryEvent))(Script_Keywords.ln(" ~ TO BE CONTINUED ~ "))(function () {
                                                                      return Script_Keywords.effect(Game_Types_Effect.GameOver.value);
                                                                  });
                                                              }));
                                                          });
                                                      });
                                                  });
                                              });
                                          });
                                      });
                                  });
                              });
                          });
                      });
                  });
              });
          });
      });
  }));
  var asString = Data_Show.show(Game_Types_Story.showStory)(story);
  exports["asString"] = asString;
  exports["story"] = story;
})(PS["Script.Scene"] = PS["Script.Scene"] || {});
(function(exports) {
  // Generated by purs version 0.12.0
  "use strict";
  var Script_Scene = PS["Script.Scene"];                 
  var asString = Script_Scene.asString;
  exports["asString"] = asString;
})(PS["Main"] = PS["Main"] || {});